# Generated by Django 5.0 on 2024-01-20 07:43

import django.db.models.deletion
import django.utils.timezone
import schedulerpages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=schedulerpages.models.id_gen, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_year_block', models.CharField(max_length=100)),
                ('descriptive_title', models.CharField(max_length=1000)),
                ('lecture_units', models.FloatField(default=0)),
                ('laboratory_units', models.FloatField(default=0)),
                ('total_units', models.FloatField(default=0)),
                ('adviser', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('TED', 'TEACHER EDUCATION DEPARTMENT'), ('CSD', 'COMPUTER STUDIES DEPARTMENT '), ('ED', 'ENGINEERING DEPARTMENT '), ('ND', 'NURSING DEPARTMENT'), ('TechEntrepD', 'TECHNOLOGY & ENTREPRENEURSHIP DEPARTMENT')], default='TED', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('instructor_id', models.CharField(max_length=100, unique=True)),
                ('instructor_name', models.CharField(max_length=100)),
                ('instructor_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.departments')),
            ],
            options={
                'abstract': False,
            },
            bases=('schedulerpages.customuser',),
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.departments')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.ManyToManyField(through='schedulerpages.InstructorCourse', to='schedulerpages.departments'),
        ),
    ]
