# Generated by Django 5.0 on 2024-02-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinedcourseschedule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='combinedcourseschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='combinedcourseschedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='combinedcourseschedule',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='combinedcourseschedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='combinedcourseschedule',
            name='time_slot',
        ),
    ]
