# Generated by Django 5.0 on 2024-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='laboratory_units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecture_units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_units',
            field=models.FloatField(default=0),
        ),
    ]
