# Generated by Django 5.0 on 2024-02-12 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.instructor')),
            ],
            options={
                'verbose_name': 'Room Schedule',
                'verbose_name_plural': 'Room Schedules',
                'ordering': ['course', 'instructor'],
                'unique_together': {('course', 'instructor')},
            },
        ),
    ]
