# Generated by Django 5.0 on 2024-01-24 07:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0002_alter_course_laboratory_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('room_type', models.CharField(max_length=100)),
                ('room_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.departments')),
            ],
        ),
    ]
