# Generated by Django 5.0 on 2024-01-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0003_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['room_name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
    ]
