# Generated by Django 5.0 on 2024-01-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0004_alter_rooms_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['department_name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
