# Generated by Django 5.0 on 2024-01-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0005_alter_departments_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.rooms')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['course', 'instructor', 'room'],
                'unique_together': {('course', 'instructor', 'room')},
            },
        ),
    ]
