# Generated by Django 5.0 on 2024-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Mon', max_length=10),
        ),
    ]
