# Generated by Django 5.0 on 2024-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0007_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory')], default='Lecture', max_length=100),
        ),
    ]
