# Generated by Django 5.0 on 2024-01-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0008_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
