# Generated by Django 5.0 on 2024-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0009_alter_schedule_time_end_alter_schedule_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
