# Generated by Django 5.0 on 2024-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0010_alter_schedule_time_end_alter_schedule_time_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Mon', max_length=10)),
            ],
            options={
                'verbose_name': 'Day of the Week',
                'verbose_name_plural': 'Days of the Week',
                'ordering': ['day'],
            },
        ),
    ]
