# Generated by Django 5.0 on 2024-01-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0012_delete_daysoftheweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('7:00 AM', '7:00 AM'), ('7:30 AM', '7:30 AM'), ('8:00 AM', '8:00 AM'), ('8:30 AM', '8:30 AM'), ('9:00 AM', '9:00 AM'), ('9:30 AM', '9:30 AM'), ('10:00 AM', '10:00 AM'), ('10:30 AM', '10:30 AM'), ('11:00 AM', '11:00 AM'), ('11:30 AM', '11:30 AM'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('1:00 PM', '1:00 PM'), ('1:30 PM', '1:30 PM'), ('2:00 PM', '2:00 PM'), ('2:30 PM', '2:30 PM'), ('3:00 PM', '3:00 PM'), ('3:30 PM', '3:30 PM'), ('4:00 PM', '4:00 PM'), ('4:30 PM', '4:30 PM'), ('5:00 PM', '5:00 PM'), ('5:30 PM', '5:30 PM'), ('6:00 PM', '6:00 PM'), ('6:30 PM', '6:30 PM'), ('7:00 PM', '7:00 PM')], default='7:00 AM', max_length=10)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['time_slot'],
                'unique_together': {('time_slot',)},
            },
        ),
    ]
