# Generated by Django 5.0 on 2024-01-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerpages', '0013_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedCourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.rooms')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerpages.time')),
            ],
            options={
                'verbose_name': 'Combined Course Schedule',
                'verbose_name_plural': 'Combined Course Schedules',
                'ordering': ['course', 'instructor', 'room', 'time_slot'],
                'unique_together': {('course', 'instructor', 'room', 'time_slot')},
            },
        ),
    ]
